// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkbpaOnazZDHufsAcrvAiFJ68s5YjvKdM',
    appId: '1:173731653314:web:6b78f68143a88f6ce77d5b',
    messagingSenderId: '173731653314',
    projectId: 'chatapp-a0c6b',
    authDomain: 'chatapp-a0c6b.firebaseapp.com',
    storageBucket: 'chatapp-a0c6b.firebasestorage.app',
    measurementId: 'G-WDX8MWENHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe1qQgiL_nzfAWZ-hU5kk75Gv9Pi4gHJE',
    appId: '1:173731653314:android:3f86812789227455e77d5b',
    messagingSenderId: '173731653314',
    projectId: 'chatapp-a0c6b',
    storageBucket: 'chatapp-a0c6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk7AUYgc7jO71oNb04Adpd7WPonz4VtTk',
    appId: '1:173731653314:ios:3b3d0995f8190446e77d5b',
    messagingSenderId: '173731653314',
    projectId: 'chatapp-a0c6b',
    storageBucket: 'chatapp-a0c6b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk7AUYgc7jO71oNb04Adpd7WPonz4VtTk',
    appId: '1:173731653314:ios:3b3d0995f8190446e77d5b',
    messagingSenderId: '173731653314',
    projectId: 'chatapp-a0c6b',
    storageBucket: 'chatapp-a0c6b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkbpaOnazZDHufsAcrvAiFJ68s5YjvKdM',
    appId: '1:173731653314:web:027693c61d5909fee77d5b',
    messagingSenderId: '173731653314',
    projectId: 'chatapp-a0c6b',
    authDomain: 'chatapp-a0c6b.firebaseapp.com',
    storageBucket: 'chatapp-a0c6b.firebasestorage.app',
    measurementId: 'G-7CZEHG7617',
  );
}
